[package]
name = "host"
version = "0.1.0"
edition = "2021"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
api = { path = "../api" }
dlopen2 = "0.4.1"
once_cell = "1"
