[package]
name = "host"
version = "0.1.0"
edition = "2021"
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
dlopen2 = "0.5.0"
once_cell = "1"
